---
apiVersion: v1
kind: Service
metadata:
  name: nginx-smtp-auth
  namespace: nginx-dev
  labels:
    app: nginx-smtp-auth
spec:
  type: ClusterIP
  selector:
    app: nginx-smtp-auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
   