---
apiVersion: v1
kind: Service
metadata:
  name: nginx-smtp
  namespace: nginx-dev
  labels:
    app: nginx-smtp
spec:
  type: ClusterIP
  selector:
    app: nginx-smtp
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
      name: tcp-smtp
    - protocol: TCP
      port: 465
      targetPort: 465
      name: tcp-smtps
    - protocol: TCP
      port: 587
      targetPort: 587
      name: tcp-smtps2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-smtp-nlb
  namespace: nginx-dev
  labels:
    app: nginx-smtp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  selector:
    app: nginx-smtp
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
      name: tcp-smtp
    - protocol: TCP
      port: 465
      targetPort: 465
      name: tcp-smtps
    - protocol: TCP
      port: 587
      targetPort: 587
      name: tcp-smtps2