apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-smtp-v1
  namespace: nginx-dev
  labels:
    app: nginx-smtp
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-smtp
      version: v1
  template:
    metadata:
      labels:
        app: nginx-smtp
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9113"
        #traffic.sidecar.istio.io/excludeOutboundPorts: "8080"
    spec:
      serviceAccountName: nginx
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nginx
        image: registry.lestak.sh:v0.0.1
        resources:
          limits:
            memory: 4000Mi
            cpu: 4000m
          requests:
            memory: 500Mi
            cpu: 100m
        ports:
        - containerPort: 25
          name: tcp-smtp
        - containerPort: 465
          name: tcp-smtps
        - containerPort: 587
          name: tcp-smtps2
      - name: metrics
        image: nginx/nginx-prometheus-exporter:0.9.0
        args:
          - "-nginx.plus"
          - "-nginx.scrape-uri=http://127.0.0.1:80/api"
          - "-prometheus.const-labels=deployment=$(DEPLOY_NAME)"
        env:
        - name: DEPLOY_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        ports:
        - containerPort: 9113
          name: metrics
        resources:
          limits:
            memory: 500Mi
            cpu: 100m
          requests:
            memory: 500Mi
            cpu: 100m